# Generated by Django 4.2.1 on 2023-05-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=300)),
                ('description', models.TextField(default='', null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('discountPercentage', models.FloatField(default=0.0, null=True)),
                ('rating', models.FloatField(default=0.0, null=True)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('brand', models.CharField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=250)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_url', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.customuser')),
            ],
        ),
    ]
